language: node_js
node_js:
- 8.9.0
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
- CXX=g++-4.8
cache:
  directories:
  - node_modules
notifications:
  email:
  - iking@lasell.edu
  slack:
    secure: UTJFVefCj2TBQJNtu2w0h4fNs39tnJKn1z22CPf+pzQwXSsY5xL/hXEIAcP2HuVBCeJ2rVu4JPh442/tNWcLynWOpRCf6PIYvyBtqwisS84pqj3dJTgyHnDmBrPonsVTeSxj76FpQ3jLxWGgiRmWdM2M+utbuIoNugWRKMzxFRSX2HOfnwlSpkklwhxOc0BwP7JVIginZOckH9GdYspQQ+X9a2IlRDIQm4+xSPIi1wB5IrbufI+mpGXlSXBL+JJAO2lxFE+3JGMwtW0Nwtw8owfOTGLyWmTi375NXM5Kz9qC2EgXrYZEjQQ6bkrOglpUP3Mz/qd9rXJALD8xjgMrTUSZVIzyKe8JxonBxGrdUiNGWbpSTiz52kwyGidK24bX4stWwr79Dn+r66wLXvgkEHZSI7rzFYTMa7IqYtCDn2yveZBEmDha24fQYCMMIWEGZ5ANAY6qEfFyB/60h1STOpDrpwv+hODZt06oUR6rOs4K9TWHB9h9OHbYY5GQrrYpVienOSu2UXNjOdDp6S2c4Ns1Pdp4fsHrX0PL3Dmsx/jg/6o++n4bWGiHkaUBZSH7nzYD4A45pqat7l2vWLuMrwBiEIx3CPXiIyb5lMeBBUuYW/Oh5s1Vl5txK8BVUhFXji7iCFerjAm8RpqWFP/qG0PkrzhzAgsTpZTy2JatT98=
install:
- npm install